site_name: 2020_5eI_Team5
nav:
    - 'Project Charter': 'Project charter.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management Plan': 'Software Project Management Plan.md'
    - 'Business Model Canvas': 'business_model_canvas.pdf'
    - 'Project Model Canvas': 'Project_Model_Canvas.pdf'
    - 'Architecture, Design and Coding Standards': 'Architecture, Design and Coding Standards.md'
    - 'Iteration plan': 'Iteration plan.md'
    - 'Memo of understanding': 'Memo of understanding.md'
    - 'Project Success Criteria': 'Project Success Criteria.md'
    - 'Release plan': 'Release plan.md'
    - 'System documentation': 'System documentation.md'
    - 'Test case specification': 'Test case specification.md'
    - 'Test Plan': 'Test Plan.md'
    - 'User guide': 'User guide.md'
    
theme:
    name: readthedocs

use_directory_urls: true
