site_name: 2020_5eI_Team5
nav:
    - 'Project Charter': 'Project charter.md'
    - 'Software Requirements Specification': 'Software Requirements Specification.md'
    - 'Software Project Management Plan': 'Software Project Management Plan.md'
    - 'Business Model Canvas': 'business_model_canvas.pdf'
    - 'Project Model Canvas': 'Project_Model_Canvas.pdf'
    - 'Architecture, Design and Coding Standards': 'Architecture, Design and Coding Standards.md'
    - 'Iteration plan': 'Iteration plan.md'
    - 'Memo of understanding': 'Memo of understanding.md'
    - 'Project Success Criteria': 'Project Success Criteria.md'
    - 'Release plan': 'Release plan.md'
    - 'System documentation': 'System documentation.md'
    - 'Test case specification': 'Test case specification.md'
    - 'Test Plan': 'Test Plan.md'
    - 'User guide': 'User guide.md'
    - 'Project Charter (PDF)': 'Project charter.pdf'
    - 'Software Requirements Specification (PDF)': 'Software Requirements Specification.pdf'
    - 'Software Project Management Plan (PDF)': 'Software Project Management Plan.pdf'
    - 'Architecture, Design and Coding Standards (PDF)': 'Architecture, Design and Coding Standards.pdf'
    - 'Iteration plan (PDF)': 'Iteration plan.pdf'
    - 'Memo of understanding (PDF)': 'Memo of understanding.pdf'
    - 'Project Success Criteria (PDF)': 'Project Success Criteria.pdf'
    - 'Release plan (PDF)': 'Release plan.pdf'
    - 'System documentation (PDF)': 'System documentation.pdf'
    - 'Test case specification (PDF)': 'Test case specification.pdf'
    - 'Test Plan (PDF)': 'Test Plan.pdf'
    - 'User guide (PDF)': 'User guide.pdf'
    
theme:
    name: readthedocs

use_directory_urls: true
